apiVersion: flightctl.io/v1beta1
kind: Device
metadata:
  labels:
    alias: edge-2
    rhel: "9.6"
    type: noapps
  name: REPLACE_WITH_UUID
spec:
  config:
  - inline:
    - content: Under new management!
      path: /etc/motd
    name: motd
